services:
  chat:
    build: .
    ports:
      - "0.0.0.0:8001:8001"
    read_only: true
    volumes:
      - ./data:/data # Will hold the chat logs to remember
      - /tmp # Anonymous volume for execution
    cap_drop:
      - ALL
