services:
  chat:
    build: .
    ports:
      - "0.0.0.0:8001:8001"
    read_only: true
    volumes:
      - ./data:/data # Will hold the chat logs to remember
      - /tmp # Anonymous volume for execution
 
    # Below not tested yet, security features to turn on #

    #networks:
    # - proxy-net
    #cap_drop:
    #  - ALL

#networks:
#  proxy-net:
#    driver: bridge
#    internal: true  # Blocks external internet access
